//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{

    public partial class Review
    {
        public int id { get; set; }
        public int rating { get; set; }
        public string body { get; set; }
        public string username { get; set; }
        public int restaurant_id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
